# Generated by Django 3.2 on 2022-06-20 12:40

import blog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=blog.fields.NonStrippingCharField(blank=True, max_length=255, null=True),
        ),
    ]
